language: python
python:
# - "3.6"
  - "3.7"
# command to install dependencies
install:
#  - pip install -r ./mysite/requirements.txt
  - pip install Flask
  - pip install SQLAlchemy 
  - pip install -U Flask-SQLAlchemy 
  - pip install Flask-WTF
  - pip install Flask-Login
  
# command to run tests
script:
  - pytest ./mysite
#-s -v
